# -*- coding: utf-8 -*-
"""Cancer Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pSphApOqB0wDhqts_HwMDMkFibX4rDNo
"""

import pandas as pd
pd.set_option("display.max_rows",None)
cancer_dict= pd.read_csv("/content/cancer_dict.csv")
data= pd.read_csv("/content/data.csv")
id_dict= pd.read_csv("/content/id_dict.csv")
data_cancer= data.merge(cancer_dict, on="cancer_code",how="left")
final_incidence = data_cancer.merge(
    id_dict,
    on='id_code',
    how='left'
)

final_incidence = final_incidence[
    [
        'CI5_continent',
        'country_code',
        'id_label',
        'registry_code',
        'sex',
        'age',
        'year',
        'cancer_label',
        'short_label',
        'icd10',
        'cases',
        'py'
    ]
]
final_incidence[['cancer_label', 'id_label']].isna().sum()
final_incidence['year'].min(), final_incidence['year'].max()
final_incidence.to_csv(
    'ci5plus_incidence_merged.csv',
    index=False
)
p1=pd.read_csv("/content/Morticd10_part1")
p2=pd.read_csv("/content/Morticd10_part2")
p3=pd.read_csv("/content/Morticd10_part3")
p4=pd.read_csv("/content/Morticd10_part4")
p5=pd.read_csv("/content/Morticd10_part4")
p6=pd.read_csv("/content/Morticd10_part5")

mortality_all = pd.concat(
    [p1, p2, p3, p4, p5, p6],
    ignore_index=True
)
mortality_cancer = mortality_all[
    mortality_all['Cause'].str.startswith('C', na=False)
]
mortality_cancer['Cause'].unique()[:10]
death_cols = [col for col in mortality_cancer.columns if col.startswith('Deaths')]

mortality_cancer['total_deaths'] = mortality_cancer[death_cols].sum(axis=1)
mortality_cancer[['Cause', 'Year', 'total_deaths']].head()
mortality_clean = mortality_cancer[
    ['Country', 'Year', 'Sex', 'Cause', 'total_deaths']
]

mortality_clean = mortality_clean[
    (mortality_clean['Year'] >= 2000) &
    (mortality_clean['Year'] <= 2025)
]
mortality_clean['Year'].min(), mortality_clean['Year'].max()
mortality_labeled = mortality_clean.merge(
    cancer_dict,
    left_on='Cause',
    right_on='icd10',
    how='left'
)
mortality_labeled[['Cause', 'cancer_label']].drop_duplicates().head(10)
mortality_final = mortality_labeled.groupby(
    ['Country', 'Year', 'cancer_label'],
    as_index=False
)['total_deaths'].sum()

print(p2.head(20))
mortality_final.to_csv(
    'who_cancer_mortality_2000_2025.csv',
    index=False
)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

incidence_df=pd.read_csv("/content/ci5plus_incidence_merged.csv")
mortality=pd.read_csv("/content/who_cancer_mortality_2000_2025.csv")

#AGGREGATE INCIDENCE DATA
incidence_agg = incidence_df.groupby(
    ['id_label', 'year', 'cancer_label'],
    as_index=False
).agg({
    'cases': 'sum',
    'py': 'sum'
})
#Renaming columns
incidence_agg=incidence_agg.rename(columns={
    'id_label': 'Country',
    'year': 'Year'
})


# converting country datatype as string for merging
mortality['Country'] = mortality['Country'].astype(str)

#Merging of incidence and mortality data
inc_mortality=incidence_agg.merge(mortality,on=["Country","Year","cancer_label"],how="left")

#Filled total_deaths null values with 0
inc_mortality['total_deaths'] = inc_mortality['total_deaths'].fillna(0)
missing_rate = inc_mortality['total_deaths'].isna().mean()
inc_mortality.groupby('Country')['total_deaths'].apply(
    lambda x: x.notna().mean()
).sort_values()
inc_mortality['MIR'] = (
    inc_mortality['total_deaths'] /
    inc_mortality['cases']
)

# Avoid division by zero
inc_mortality.loc[
    inc_mortality['cases'] == 0, 'MIR'
] = None

analysis_df = inc_mortality[
    (inc_mortality['cases'] > 0)
].copy()

# Makin Year as int type
incidence_agg['Year'] = incidence_agg['Year'].astype(int)

# Filter years
inc_global = incidence_agg[
    (incidence_agg['Year'] >= 2000) &
    (incidence_agg['Year'] <= 2025)
]

# Global cancer incidence
global_incidence = analysis_df.groupby(
    'Year', as_index=False
)['cases'].sum()

plt.figure(figsize=(10,6))
plt.plot(global_incidence['Year'], global_incidence['cases'])
plt.title('Global Cancer Incidence (1950-2020)')
plt.xlabel('Year')
plt.ylabel('Number of Cases')
plt.grid(True)
plt.show()


#Global cancer Mortality
mortality_global = mortality.groupby(
    'Year', as_index=False
)['total_deaths'].sum()

plt.figure(figsize=(10,6))
plt.plot(mortality_global['Year'], mortality_global['total_deaths'])

plt.xticks(
    sorted(mortality_global['Year'].unique()),
    rotation=45
)

plt.title('Global Cancer Mortality (2000–2020)')
plt.xlabel('Year')
plt.ylabel('Number of Deaths')
plt.grid(True)
plt.tight_layout()
plt.show()


 # GLOBAL INCIDENCE
global_incidence = incidence_agg.groupby(
    'Year', as_index=False
)['cases'].sum()

# GLOBAL MORTALITY
global_mortality = mortality.groupby(
    'Year', as_index=False
)['total_deaths'].sum()

# MERGE BY YEAR
global_compare = global_incidence.merge(
    global_mortality,
    on='Year',
    how='inner'
)

#Global Cancer Incidence vs Mortality
fig, ax1 = plt.subplots(figsize=(10,6))

ax1.plot(global_compare['Year'], global_compare['cases'])
ax1.set_ylabel('Incidence (cases)')
ax1.set_xlabel('Year')

ax2 = ax1.twinx()
ax2.plot(
    global_compare['Year'],
    global_compare['total_deaths'],
    linestyle='--',
    color="red"
)
ax2.set_ylabel('Mortality (deaths)')

ax1.set_xticks(
    sorted(global_compare['Year'].unique())
)

plt.title('Global Cancer Incidence vs Mortality (2000–2020)')
plt.grid(True)
plt.tight_layout()
plt.show()


#Top 10 Cancers by Incidence (CI5plus)'
inc_cancer = inc_global.groupby(
    'cancer_label', as_index=False
)['cases'].sum()

top_incidence = inc_cancer.sort_values(
    'cases', ascending=False
).head(10)

plt.figure(figsize=(10,6))
plt.barh(top_incidence['cancer_label'], top_incidence['cases'])
plt.xlabel('Number of Cases')
plt.title('Top 10 Cancers by Incidence (CI5plus)')
plt.gca().invert_yaxis()
plt.grid(True)
plt.show()

#Top 10 Cancers by Mortality (WHO)
mort_cancer = mort_global.groupby('cancer_label', as_index=False
)['total_deaths'].sum()

top_mortality = mort_cancer.sort_values(
    'total_deaths', ascending=False
).head(10)

plt.figure(figsize=(10,6))
plt.barh(top_mortality['cancer_label'], top_mortality['total_deaths'])
plt.xlabel('Number of Deaths')
plt.title('Top 10 Cancers by Mortality (WHO)')
plt.gca().invert_yaxis()
plt.grid(True)
plt.show()

#Global MIR by Cancer Type (Approximate)
mir_global = inc_cancer.merge(
    mort_cancer,
    on='cancer_label',
    how='inner'
)

mir_global['MIR'] = (
    mir_global['total_deaths'] /
    mir_global['cases']
)

top_mir = mir_global.sort_values(
    'MIR', ascending=False
).head(10)
colors = plt.cm.tab10(np.linspace(0, 1, len(top_mir)))
plt.figure(figsize=(10,6))
plt.barh(top_mir['cancer_label'], top_mir['MIR'],color=colors)
plt.xlabel('Mortality-to-Incidence Ratio (MIR)')
plt.title('Global MIR by Cancer Type (Approximate)')
plt.gca().invert_yaxis()
plt.grid(True)
plt.show()